version: "3.7"
services:
  server:
    image: eden-hello-world
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5656:5656"
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ${PWD}/results:/usr/local/results
      - ${PWD}/logs/:/logs
    command: --num-workers 4 --port 5656 --logfile /logs/logs.log
  redis:
    image: redis
