name: Docker CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Docker meta 
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: abrahamofeden/eden-hello-world

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'       
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
